name: EventCapslueToy
version: 1.0
api-version: 1.15
description: event capsluetoy.
author: kubotan
main: space.gorogoro.eventcapsluetoy.EventCapslueToy

commands:
  eventcapsluetoy:
    description: Commands to manage your event capsluetoy
    usage: |
      Use /help eventcapsluetoy [subcommand] for more information
      /<command> list - List all capsluetoy
      /<command> modify <capsluetoy_name> - Modify a capsluetoy
      /<command> delete <capsluetoy_name> - Delete a capsluetoy
      /<command> ticket <player_name> - Issue a ticket
  eventcapsluetoy list:
    description: List all capsluetoy
    usage: /<command> list
  eventcapsluetoy modify:
    description: Modify a capsluetoy chest
    usage: /<command> modify <capsluetoy_name>
  eventcapsluetoy delete:
    description: Delete a capsluetoy
    usage: /<command> delete <capsluetoy_name>
  eventcapsluetoy ticket:
    description: Issue a ticket
    usage: /<command> ticket <player_name>
